# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9726b7ce9137aa6bbf5336bdce5becf17270b4d4a59b082b2a63207825bfe11d25e37d725fc80ed5aa0a201047fc32c5002207edaffa5d39cc387f0753c0dd2b

test:
  secret_key_base: 1130f4ddc2de140b2d8c249fda046c5df3540bdac620bd9df36e8eb01a1382c3ef0669931f99495b81aa0faf555ef4ef562550351fa95ba055e90691a0343af2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
